// client/src/components/Search.vue
<template>
  <section class="search">
    <h1>Get your Super Hero Name</h1>
    <!-- v.on handles events -->
    <form v-om:submit.prevent="onSubmit">
      <div class="form-group">
        <label for="surname">Surname</label>
        <input type="text" id="surname" name="surname" v-model="surname" placeholder="John" />
      </div>
      <div class="form-group">
        <label for="givenname">Givenname</label>
        <input type="text" id="givenname" name="surname" v-model="givenname" placeholder="Doe"/>
      </div>
      <div class="form-group">
        <input type="submit" value="Get Super Hero Name" class="btn">
      </div>
    </form>
  </section>
</template>

<script>
export default {
  name: 'Search',
  data() {
    return {
      surname: "", 
      givenname: ""
    }
  },
  beforeCreate(){
    document.body.className = "body-bg-image";
  }
};
</script>

<style>
</style>

// clientApp/src/app/components/search/search.component.ts
import { Component, OnInit } from '@angular/core';
import { HeroService } from 'src/app/services/hero.service';
import { User } from 'src/app/models/user';

@Component({
  selector: 'hero-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css']
})
export class SearchComponent implements OnInit {

  constructor(private heroservice: HeroService) { }

  ngOnInit() {
  }

  submitted = false;
  model = new User();

  getHeroName() {
    this.submitted = true;
    this.heroservice.getSuperHeroName(this.model)
      .subscribe(response => this.model = {
        superHero: response
      });
  }
  // TODO: Remove this when done testing
  get diagnostic() { return JSON.stringify(this.model); }

}

<section class="search">
  <h1>Get your Super Hero Name</h1>
  <!-- v.on handles events -->
  <form v-on:submit.prevent="onSubmit">
    <div class="form-group">
      <label for="surname">Surname</label>
      <input type="text" id="surname" name="surname" v-model="surname" placeholder="John" />
    </div>
    <div class="form-group">
      <label for="givenname">Givenname</label>
      <input type="text" id="givenname" name="surname" v-model="givenname" placeholder="Doe" />
    </div>
    <div class="form-group">
      <!-- <input type="submit" value="Get Super Hero Name" class="btn"> -->
      <input type="submit" value="Get Super Hero Name" class="btn" [disabled]="!heroForm.form.valid">
    </div>
  </form>
</section>
